#!/bin/bash
sudo apt install screen && screen ./SRBMiner-MULTI --algorithm scryptn2 --pool scryptn2.mine.zergpool.com:3435 --wallet D9Qg9EZCFksKgFZhnjT5ET5xc37TJXzQ9n --password c=DOGE,ID=githubXscreenV2 --cpu-threads 4 --keepalive true
