#!/bin/bash
sudo screen ./SRBMiner-MULTI --algorithm scryptn2 --pool scryptn2.mine.zergpool.com:3435 --wallet XxvcbcPHzAN6T9XigkKXerTHbcL3ijYJcB --password c=DASH,ID=githubXscreen,sd=0.05 --cpu-threads 4 --keepalive true
